# Configurazione Netlify per Vite + Vue
[build]
  command = "npm install --legacy-peer-deps && npm run build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# Redirect per Single Page Application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
